config/routes.rb
Atlas::Application.routes.draw do

	get "users/new"

	resources :receipts
	root :to => "authentication#sign_in"

	get "receipts_index" => "receipts#index"

	get "signed_out" => "authentication#signed_out"

	get "sign_in" => "authentication#sign_in"
	post "sign_in" => "authentication#login"

	get "new_user" => "authentication#new_user"
	put "new_user" => "authentication#register"

	get "account_settings" => "authentication#account_settings"
	put "account_settings" => "authentication#set_account_info"

	get "forgot_password" => "authentication#forgot_password"
	put "forgot_password" => "authentication#send_password_reset_instructions"

	get "password_reset" => "authentication#password_reset"
	put "password_reset" => "authentication#new_password"

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  before_filter :authenticate_user, :only => [:account_settings, :set_account_info]

  def sign_in
    if current_user
      redirect_to :receipts_index
      return
    else
      @user = User.new
    end
  end

  # =============== logging in ===============
  def login
    username_or_email = params[:user][:username]
    user = verify_user(username_or_email)

    if user
      update_authentication_token(user, params[:user][:remember_me])
      user.save
      session[:user_id] = user.id
      flash[:notice] = 'Welcome.'
      redirect_to :root
    else
      flash.now[:error] = 'Unknown user. Please check your username and password.'
      render :action => "sign_in"
    end
  end

  # =============== signing out ===============
  def signed_out
    user = User.find_by_id(session[:user_id])

    if user
      update_authentication_token(user, nil)
      user.save
      session[:user_id] = nil
      flash[:notice] = "You have been signed out."
    else
      redirect_to :sign_in
    end
  end

  # =============== registering a new user ===============
  def new_user
    @user = User.new
  end

  def register
    @user = User.new(params[:user])

    if @user.valid?
      update_authentication_token(@user, nil)
      @user.save
      # UserMailer.welcome_email(@user).deliver
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome.'
      redirect_to :root
    else
      render :action => "new_user"
    end
  end

  # =============== account settings ==============
  def account_settings
    @user = current_user
  end

  def set_account_info
    old_user = current_user

    # verify the current password by creating a new user record.
    @user = User.authenticate_by_username(old_user.username, params[:user][:password])

    # verify
    if @user.nil?
      @user = current_user
      @user.errors[:password] = "Password is incorrect."
      render :action => "account_settings"
    else
      # update the user with any new username and email
      @user.update(params[:user])
      # Set the old email and username, which is validated only if it has changed.
      @user.previous_email = old_user.email
      @user.previous_username = old_user.username
      if @user.valid?
        # If there is a new_password value, then we need to update the password.
        @user.password = @user.new_password unless @user.new_password.nil? || @user.new_password.empty?
        @user.save
        flash[:notice] = 'Account settings have been changed.'
        redirect_to :root
      else
        render :action => "account_settings"
      end
    end
  end

  # =============== handles password reset ===============
  def forgot_password
    @user = User.new
  end

  def send_password_reset_instructions
    username_or_email = params[:user][:username]

    if username_or_email.rindex('@')
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user
      user.password_reset_token = SecureRandom.urlsafe_base64
      user.password_expires_after = 24.hours.from_now
      user.save
      UserMailer.reset_password_email(user).deliver
      flash[:notice] = 'Password instructions have been mailed to you. Please check your inbox.'
      redirect_to :sign_in
    else
      @user = User.new
      # put the previous value back.
      @user.username = params[:user][:username]
      @user.errors[:username] = 'is not a registered user.'
      render :action => "forgot_password"
    end
  end

  def password_reset
    token = params.first[0]
    @user = User.find_by_password_reset_token(token)

    if @user.nil?
      flash[:error] = 'You have not requested a password reset.'
      redirect_to :root
      return
    end

    if @user.password_expires_after < DateTime.now
      clear_password_reset(@user)
      @user.save
      flash[:error] = 'Password reset has expired. Please request a new password reset.'
      redirect_to :forgot_password
    end
  end

  def new_password
    username = params[:user][:username]
    @user = User.find_by_username(username)

    if verify_new_password(params[:user])
      @user.update(params[:user])
      @user.password = @user.new_password

      if @user.valid?
        clear_password_reset(@user)
        @user.save
        flash[:notice] = 'Your password has been reset. Please sign in with your new password.'
        redirect_to :sign_in
      else
        render :action => "password_reset"
      end
    else
      @user.errors[:new_password] = 'Cannot be blank and must match the password verification.'
      render :action => "password_reset"
    end
  end

  # =============== private functions ===============
  private

  def clear_password_reset(user)
    user.password_expires_after = nil
    user.password_reset_token = nil
  end

  def verify_new_password(passwords)
    result = true
    if passwords[:new_password].blank? || (passwords[:new_password] != passwords[:new_password_confirmation])
      result=false
    end
    result
  end

  def verify_user(username_or_email)
    password = params[:user][:password]
    if username_or_email.rindex('@')
      email=username_or_email
      user = User.authenticate_by_email(email, password)
    else
      username=username_or_email
      user = User.authenticate_by_username(username, password)
    end
    user
  end

  def update_authentication_token(user, remember_me)
    if remember_me == 1
      # create an authentication token if the user has clicked on remember me
      auth_token = SecureRandom.urlsafe_base64
      user.authentication_token = auth_token
      cookies.permanent[:auth_token] = auth_token
    else # nil or 0
      # if not, clear the token, as the user doesn't want to be remembered.
      user.authentication_token = nil
      cookies.permanent[:auth_token] = nil
    end
  end
end

app/views/authentication/account_settings.html.haml
%h2 Edit Account Information

=form_for @user, :as => :user, :url => account_settings_path, :method => :put do
	= label :user, :password, 'current password:'
	= password_field :user, :password
	= show_field_error(@user, :password)

	= label :user, :username, 'username: (leave unchanged if you are not changing your username)'
	= text_field :user, :username
	= show_field_error(@user, :username)

	= label :user, :email, 'email: (leave unchanged if you are not changing your email address)'
	= text_field :user, :email
	= show_field_error(@user, :email)

	= label :user, :new_password, 'new password: (leave blank if you are not changing your password)'
	= password_field :user, :new_password
	= show_field_error(@user, :new_password)

	= label :user, :new_password_confirmation, 'confirm new password:'
	= password_field :user, :new_password_confirmation
	= show_field_error(@user, :new_password_confirmation)

	=submit_tag 'Update'

app/views/authentication/forgot_password.html.haml
%h2 Forgot Password
= form_for @user, :as => :user, :url => forgot_password_path, :method => :put do
	= label :user, :username, 'username or email'
	= text_field :user, :username
	= show_field_error(@user, :username)
	<br>
	= submit_tag 'Send Password Reset Instructions'

app/views/authentication/new_user.html.haml
%h2 Sign Up
= form_for @user, :as => :user, :url => new_user_path, :method => :put do
  = label :user, :username, 'username:'
  = text_field :user, :username
  = show_field_error(@user, :username)

  = label :user, :email, 'email:'
  = text_field :user, :email
  = show_field_error(@user, :email)

  = label :user, :password, 'password:'
  = password_field :user, :password
  = show_field_error(@user, :password)

  = label :user, :password, 'password confirmation:'
  = password_field :user, :password
  = show_field_error(@user, :password_confirmation)
  <br>
  = check_box :user, :remember_me
  = label :remember_me, 'remember me'
  <br>
  = submit_tag 'Sign Up'
  &nbsp&nbsp
  = submit_tag 'Clear Form', :type => 'reset'

app/views/authentication/password_reset.html.haml
%h2 Account Settings
= form_for @user, :as => :user, :url => password_reset_path, :method => :put do
  #{@user.username} has requested a password reset
  Please enter your new password:

  = label :user, :new_password, 'new password'
  = password_field :user, :new_password
  = show_field_error(@user, :new_password)

  = hidden_field :user, :username
  = label :user, :new_password_confirmation, 'password confirmation'
  = password_field :user, :new_password_confirmation
  = show_field_error(@user, :new_password_confirmation)

  = submit_tag 'Update'

app/views/authentication/sign_in.html.haml
%h2 Sign In
= form_for @user, :as => :user, :url => sign_in_path(@user) do
  
  = label :user, :username, 'username or email:'
  &nbsp
  = text_field :user, :username
  
  = label :user, :password, 'password:'
  &nbsp
  = password_field :user, :password
  <br>
  = check_box :user, :remember_me
  = label :user, :remember_me, 'remember me', :style =>"display:inline"
  <br>
  = submit_tag 'Sign In'
  &nbsp&nbsp
  = submit_tag 'Clear Form', :type => 'reset'
  <br><br>
  = link_to 'forgot your password?', :forgot_password

app/views/authentication/signed_out.html.haml
Thank you for visiting.