config/routes.rb
Atlas::Application.routes.draw do

	get "users/new"

	resources :receipts
	root :to => "authentication#sign_in"

	get "receipts_index" => "receipts#index"

	get "signed_out" => "authentication#signed_out"

	get "sign_in" => "authentication#sign_in"
	post "sign_in" => "authentication#login"

	get "new_user" => "authentication#new_user"
	put "new_user" => "authentication#register"

	get "account_settings" => "authentication#account_settings"
	put "account_settings" => "authentication#set_account_info"

	get "forgot_password" => "authentication#forgot_password"
	put "forgot_password" => "authentication#send_password_reset_instructions"

	get "password_reset" => "authentication#password_reset"
	put "password_reset" => "authentication#new_password"

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
	attr_accessible :date, :cost, :payment, :store, :usern
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

	def show
  	id = params[:id] # retrieve receipt ID from URI route
  	@receipt = Receipt.find(id) # look up receipt by unique ID
  	# will render app/views/receipts/show.html.haml by default
	end

  def index
	sort = params[:sort] #|| session[:sort]
	now = DateTime.now
	case sort
  when 'dateasc'
    ordering,@date_header = {:order => :dateasc}, 'hilite'
    @receipts = Receipt.order("date").where("usern = (?) and (?) > date", current_user.username, now)
    return
  when 'datedesc'
    ordering,@date_header = {:order => :datedesc}, 'hilite'
    @receipts = Receipt.order("date DESC").where("usern = (?) and (?) > date", current_user.username, now)
    return
	when 'costasc'
		ordering,@cost_header = {:order => :costasc}, 'hilite'
		@receipts = Receipt.order("cost").where("usern = (?) and (?) > date", current_user.username, now)
		return
  when 'costdesc'
    ordering,@cost_header = {:order => :costdesc}, 'hilite'
    @receipts = Receipt.order("cost DESC").where("usern = (?) and (?) > date", current_user.username, now)
    return
  when 'store'
    ordering,@store_header = {:order => :store}, 'hilite'
    @receipts = Receipt.where("store = (?) and usern = (?) and (?) > date", params[:sto], current_user.username, now)
    return
  when 'payment'
    ordering,@payment_header = {:order => :payment}, 'hilite'
  	@receipts = Receipt.where("payment = (?) and usern = (?) and (?) > date", params[:pay], current_user.username, now)
  	return
  end
  @receipts = Receipt.order("date").where("usern = (?) and (?) > date", current_user.username, now)
  end

	def new
  		# default: render 'new' template
	end

	def create
  		@receipt = Receipt.create!(params[:receipt])
  		flash[:notice] = "Receipt was successfully created."
  		redirect_to receipts_path
	end
 
	def update
  		@receipt = Receipt.find params[:id]
  		@receipt.update_attributes!(params[:receipt])
  		flash[:notice] = "Receipt was successfully updated."
  		redirect_to receipt_path(@receipt)
	end

	def destroy
  		@receipt = Receipt.find(params[:id])
  		@receipt.destroy
  		flash[:notice] = "Receipt was successfully deleted."
  		redirect_to receipts_path
	end
end

app/views/receipts/index.html.haml
-#  This file is app/views/receipts/index.html.haml
%h1 All Receipts



%table#receipts
  %thead
    %tr
      //%th Purchase Date
      %th{:class => @date_header}= link_to 'Purchase Date', if (params[:sort] == 'dateasc') then receipts_path(:sort => 'datedesc') else receipts_path(:sort => 'dateasc')end, :id => 'purchase_date_header'
      //%th Cost
      %th{:class => @cost_header}= link_to 'Cost', if (params[:sort] == 'costasc') then receipts_path(:sort => 'costdesc') else receipts_path(:sort => 'costasc')end, :id => 'cost_header'
      %th Store
      %th Payment Type
  %tbody
    - @receipts.each do |receipt|
      %tr
        %td= link_to receipt.date.strftime("Purchase made on %B %-d, %Y at %l:%M.%S %P"), receipt_path(receipt)
        %td= "$%.2f" % receipt.cost
        %td{:class => @store_header}= link_to receipt.store, receipts_path(:sort => 'store', :sto => receipt.store), :id => 'store_header'
        %td{:class => @payment_header}= link_to (if (receipt.payment.downcase == "cash") then "Cash" else "xxxx-xxxx-xxxx-#{receipt.payment}" end), receipts_path(:sort => 'payment', :pay => receipt.payment), :id => 'payment_header'

&nbsp
= link_to 'All Receipts', receipts_path(:sort => 'date', :id => 'purchase_date_header')
&nbsp
= link_to 'Add new receipt', new_receipt_path

app/views/receipts/new.html.haml
%h2 Create New Receipt

= form_tag receipts_path, :method => :post do
  
  = label :receipt, :usern, current_user.username
  = hidden_field :receipt, :usern, :value => current_user.username

  = label :receipt, :date, 'Date'
  = datetime_select :receipt, :date
 
  = label :receipt, :cost, 'Cost'
  = text_field :receipt, :cost

  = label :receipt, :payment, 'Payment Method'
  = text_field :receipt, :payment

  = label :receipt, :store, 'Store'
  = text_field :receipt, :store
  <br>
  = submit_tag 'Save Changes'

app/views/receipts/show.html.haml
-# in app/views/receipts/show.html.haml

%h2 Details about your receipt

%ul#details
  %li
    Cost: 
    = "$#{@receipt.cost}"
  %li
    Purchased on:
    = @receipt.date.strftime("%B %d, %Y %l:%M.%S %P")
    at 
    = @receipt.store

= button_to 'Delete', receipt_path(@receipt), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to receipt list', receipts_path